var fs = require('fs');
var path = require('path');

var conf = {
  SYSTEM_EMAIL: 'info@visav.io',
  APP_ID: 'com.krisandbrake.Phlex',
  APP_DESCRIPTION: 'Phlex RS',
  APP_NAME: 'Phlex RS',
  APP_OWNER: 'E Brake',
  AWS_IOT_CONFIG: {
    accessKeyId: 'AKIAJMXV7C4RR4AVLVUQ',
    secretAccessKey: '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',
    endpointAddress: 'azf5xkj2sjl2t.iot.us-west-2.amazonaws.com',
    region: 'us-west-2'
  }
};

//--- Helper functions ---

function readCredentialsFile(name) {  
  return fs.readFileSync(
    path.resolve(__dirname, 'server/credentials', name),
    'UTF-8'
  );
}

// Apple Push Notification Certificates
var apnsEnvIdentifier = (process.env.NODE_ENV==='development' ? 'dev' : 'prod');
conf.apnsCertData = readCredentialsFile('phlex_'+apnsEnvIdentifier+'_cert.pem');
conf.apnsKeyData = readCredentialsFile('phlex_'+apnsEnvIdentifier+'_key.pem');

// Google Push Notifications
// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
// conf.gcmServerApiKey = 'Your-server-api-key';

module.exports = conf;
