var fs = require('fs');
var path = require('path');

var conf = {
  SYSTEM_EMAIL: 'info@visav.io'
};

// Google Push Notifications
// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
// conf.gcmServerApiKey = 'Your-server-api-key';

//--- Helper functions ---

function readCredentialsFile(name) {  
  return fs.readFileSync(
    path.resolve(__dirname, 'server/credentials', name),
    'UTF-8'
  );
}

// Apple Push Notification Certificates
var apnsEnvIdentifier = (process.env.NODE_ENV==='development' ? 'dev' : 'prod');
conf.apnsCertData = readCredentialsFile('phlex_'+apnsEnvIdentifier+'_cert.pem');
conf.apnsKeyData = readCredentialsFile('phlex_'+apnsEnvIdentifier+'_key.pem');
conf.gcmServerApiKey = '';
conf.appName = 'Phlex';
conf.appId = 'com.krisandbrake.Phlex';
conf.applicationUserId = 'strongloop';

module.exports = conf;
